export const PRODUCTS = [
  {
    id: 1, name: "ESP LTD MT-I", brand: "ESP", category: "guitar",
    price: 42900, salePrice: 35900, sku: "ESP LTD MT-I",
    stock: 5, rating: 4.8, reviews: 142,
    image: "https://image.makewebcdn.com/makeweb/m_1920x0/zJLuM632I/DefaultData/502779260_1243781867358206_8172474463806899988_n.jpg",
    images: [
      "https://image.makewebcdn.com/makeweb/m_1920x0/zJLuM632I/DefaultData/502779260_1243781867358206_8172474463806899988_n.jpg",
      "https://image.makewebcdn.com/makeweb/m_1920x0/zJLuM632I/DefaultData/502779260_1243781867358206_8172474463806899988_n.jpg",
    ],
    description: "The ESP LTD EC-1000 delivers professional-grade tone and playability. Set-neck construction with mahogany body and top flame maple top. Seymour Duncan pickups for crushing heavy tones.",
    specs: { body: "Mahogany with Flame Maple Top", neck: "3-Piece Maple Set-Thru", scale: "24.75\"", pickups: "Seymour Duncan JB/Jazz", finish: "See-Thru Black Cherry" },
    tags: ["electric", "metal", "seymour-duncan"],
    isNew: false, isFeatured: true,
  },
  {
    id: 2, name: "Ibanez K7YIN Munky Korn Signature 7-String Electric Guitar", brand: "Ibanez", category: "guitar",
    price: 38500, salePrice: null, sku: "IBZ-RG550-WH",
    stock: 3, rating: 4.7, reviews: 89,
    image: "https://www.musicworks.co.nz/content/products/ibanez-k7yin-munky-korn-signature-7-string-electric-guitar-k7yin-0327447001754356526.jpg?canvas=1:1&width=2500",
    images: ["https://www.musicworks.co.nz/content/products/ibanez-k7yin-munky-korn-signature-7-string-electric-guitar-k7yin-0327447001754356526.jpg?canvas=1:1&width=2500"],
    description: "The original Ibanez RG550 Genesis reissue. Basswood body, maple neck with original-style Edge tremolo. Pure 80s/90s shred machine with modern reliability.",
    specs: { body: "Basswood", neck: "Maple Bolt-On", scale: "25.5\"", pickups: "DiMarzio IBZ (V7/V8/S1)", finish: "White" },
    tags: ["electric", "shred", "dimarzio"],
    isNew: true, isFeatured: true,
  },
  {
    id: 3, name: "Gibson Les Paul Standard '60s", brand: "Gibson", category: "guitar",
    price: 98000, salePrice: 89000, sku: "GIB-LP60S-HB",
    stock: 2, rating: 4.9, reviews: 214,
    image: "https://nafiriguitar.com/cdn/shop/files/FullSizeRender_38afe023-ee0c-48df-b8ae-185b0ac63f0a.jpg?v=1734496189&width=1946",
    images: ["https://nafiriguitar.com/cdn/shop/files/FullSizeRender_38afe023-ee0c-48df-b8ae-185b0ac63f0a.jpg?v=1734496189&width=1946"],
    description: "The iconic Les Paul in its '60s configuration. Slim-taper neck profile for speed and comfort. Burstbucker Pro pickups capture the classic PAF sound with modern clarity.",
    specs: { body: "Mahogany with AAA Maple Top", neck: "Mahogany Set-Neck", scale: "24.75\"", pickups: "Burstbucker Pro (Neck/Bridge)", finish: "Iced Tea Burst" },
    tags: ["electric", "vintage", "classic-rock"],
    isNew: false, isFeatured: true,
  },
  {
    id: 4, name: "Fender American Ultra Stratocaster", brand: "Fender", category: "guitar",
    price: 85000, salePrice: null, sku: "FEN-AMULT-STRAT-US",
    stock: 4, rating: 4.7, reviews: 178,
    image: "https://nafiriguitar.com/cdn/shop/products/200406154524_Epi_203_ori.jpg?v=1708515024",
    images: ["https://nafiriguitar.com/cdn/shop/products/200406154524_Epi_203_ori.jpg?v=1708515024"],
    description: "America's flagship Stratocaster. Ultra Noiseless pickups, compound-radius fingerboard, and a sculpted neck heel for unrestricted upper-fret access.",
    specs: { body: "Alder", neck: "Maple Modern D Shape", scale: "25.5\"", pickups: "Ultra Noiseless x3", finish: "Ultraburst" },
    tags: ["electric", "vintage", "americana"],
    isNew: true, isFeatured: true,
  },
  {
    id: 5, name: "Schecter Hellraiser C-1", brand: "Schecter", category: "guitar",
    price: 45000, salePrice: 38000, sku: "SCH-HELL-C1-BCH",
    stock: 6, rating: 4.6, reviews: 95,
    image: "https://nafiriguitar.com/cdn/shop/files/131995C8-B3FD-4F0D-93E2-028FFCEC0934.jpg?v=1772706159&width=1946",
    images: ["https://nafiriguitar.com/cdn/shop/files/131995C8-B3FD-4F0D-93E2-028FFCEC0934.jpg?v=1772706159&width=1946"],
    description: "Built for maximum brutality. EMG active pickups, mahogany body with quilted maple top, and TonePros locking TOM bridge. The ultimate metal machine.",
    specs: { body: "Mahogany with Quilted Maple", neck: "3-Piece Maple Set-Neck", scale: "25.5\"", pickups: "EMG 81/89", finish: "Black Cherry" },
    tags: ["electric", "metal", "emg"],
    isNew: false, isFeatured: true,
  },
  {
    id: 6, name: "Roland TD-17KVX V-Drums", brand: "Roland", category: "drums",
    price: 89900, salePrice: 79900, sku: "ROL-TD17KVX",
    stock: 2, rating: 4.8, reviews: 67,
    image: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=600&auto=format",
    images: ["https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=600&auto=format"],
    description: "Roland's pro-level V-Drum kit. Mesh heads for realistic feel, advanced TD-17 module with Bluetooth, and fully customizable kit configurations.",
    specs: { snare: "PDX-12 Mesh Pad", kick: "KD-120BK Kick Tower", cymbals: "CY-13R/12R/8V", module: "TD-17 w/ Bluetooth", pads: "6 Full Mesh Kit" },
    tags: ["drums", "electronic", "practice"],
    isNew: false, isFeatured: true,
  },
  {
    id: 7, name: "Korg Minilogue XD Synthesizer", brand: "Korg", category: "keys",
    price: 28900, salePrice: 24900, sku: "KRG-MINIXD-BLK",
    stock: 8, rating: 4.7, reviews: 203,
    image: "https://cdn.korg.com/us/products/upload/38a795cff895b157edb34e61df94fe4d.jpg",
    images: ["https://cdn.korg.com/us/products/upload/38a795cff895b157edb34e61df94fe4d.jpg"],
    description: "4-voice polyphonic analog synthesizer with digital multi-engine. Programmable arpeggiator, 16-step sequencer, and extensive effects. Pure analog oscillators with modern digital flexibility.",
    specs: { voices: "4-voice Polyphonic", oscillators: "2 VCO + Multi-Engine", effects: "Delay, Reverb, Chorus", sequencer: "16-step Programmable", keys: "37 mini-keys" },
    tags: ["synth", "analog", "polyphonic"],
    isNew: false, isFeatured: true,
  },
  {
    id: 8, name: "Pioneer DDJ-REV7 DJ Controller", brand: "Pioneer", category: "dj",
    price: 72000, salePrice: null, sku: "PIO-DDJREV7",
    stock: 3, rating: 4.9, reviews: 44,
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format",
    images: ["https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format"],
    description: "The scratch-focused 2-channel DJ controller. Motorized platters, Serato DJ Pro compatibility, and an inverted-fader layout inspired by the DJM-S9 mixer.",
    specs: { platters: "7\" Motorized", channels: "2-Channel", software: "Serato DJ Pro", inputs: "2x Phono/Line", connection: "USB-C" },
    tags: ["dj", "serato", "scratch"],
    isNew: true, isFeatured: false,
  },
  {
    id: 9, name: "Markbass Little Mark 800 Bass Amp", brand: "Markbass", category: "bass",
    price: 32500, salePrice: 28000, sku: "MRK-LM800",
    stock: 4, rating: 4.6, reviews: 38,
    image: "https://i.ytimg.com/vi/r_5KsC6eZ3M/sddefault.jpg",
    images: ["https://i.ytimg.com/vi/r_5KsC6eZ3M/sddefault.jpg"],
    description: "800W of class D power in an ultra-compact chassis. VPF and VLE filters for instant tone shaping, 4-band EQ, and unparalleled Italian bass tone.",
    specs: { power: "800W @ 4Ω", weight: "2.8kg", EQ: "4-Band Active", filters: "VPF + VLE", connection: "Speakon + 1/4\"" },
    tags: ["bass", "amplifier", "class-d"],
    isNew: false, isFeatured: false,
  },
  {
    id: 10, name: "Ibanez SR300E-JSM", brand: "Ibanez", category: "bass",
    price: 58000, salePrice: null, sku: "SPC-NSDIM5-BLK",
    stock: 2, rating: 4.8, reviews: 29,
    image: "https://www.artiesmusic.com.au/assets/alt_3/6042860.png?20220825162849",
    images: ["https://www.artiesmusic.com.au/assets/alt_3/6042860.png?20220825162849"],
    description: "5-string bass with Fishman Fluence pickups and TonePump Jr. preamp. Spector's legendary curved body contour and neck-through construction for ultimate sustain.",
    specs: { strings: "5-string", construction: "Neck-Through", pickups: "Fishman Fluence", preamp: "TonePump Jr.", finish: "Black Gloss" },
    tags: ["bass", "5-string", "fishman"],
    isNew: true, isFeatured: false,
  },
  {
    id: 11, name: "DW 5000 Series Double Bass Pedal", brand: "DW", category: "drums",
    price: 18900, salePrice: 15900, sku: "DW-5000TD",
    stock: 10, rating: 4.7, reviews: 88,
    image: "https://musicspace.co.th/wp-content/uploads/2017/02/dw5000_cp5002_double_bass_drum_pedal.webp",
    images: ["https://musicspace.co.th/wp-content/uploads/2017/02/dw5000_cp5002_double_bass_drum_pedal.webp"],
    description: "The industry-standard double bass pedal. Turbo Drive cam system, delta ball-bearing action, and fully adjustable beater angle. Battle-tested by pros worldwide.",
    specs: { type: "Double Pedal", cam: "Turbo Drive", spring: "Memory Lock System", beater: "Hard Felt/Plastic Combo", finish: "Chrome" },
    tags: ["drums", "double-pedal", "hardware"],
    isNew: false, isFeatured: false,
  },
  {
    id: 12, name: "Shure SM57 Instrument Microphone", brand: "Shure", category: "accessories",
    price: 3500, salePrice: null, sku: "SHR-SM57-LC",
    stock: 25, rating: 4.9, reviews: 512,
    image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format",
    images: ["https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=600&auto=format"],
    description: "The world's most versatile instrument microphone. Industry-standard for recording guitar amps, snare drums, brass, and woodwinds for over 60 years.",
    specs: { type: "Dynamic Cardioid", frequency: "40Hz-15kHz", SPL: "Maximum 150dB", output: "XLR", finish: "Matte Silver" },
    tags: ["microphone", "dynamic", "recording"],
    isNew: false, isFeatured: false,
  },
  {
    id: 13, name: "Ernie Ball 10-52 Heavy Bottom Strings", brand: "Ernie Ball", category: "accessories",
    price: 290, salePrice: null, sku: "EB-2215-HBTOP",
    stock: 100, rating: 4.8, reviews: 892,
    image: "https://www.musicarms.net/wp-content/uploads/2019/01/Ernie-Ball-HEAVY-BOTTOM.jpg",
    images: ["https://www.musicarms.net/wp-content/uploads/2019/01/Ernie-Ball-HEAVY-BOTTOM.jpg"],
    description: "The go-to strings for heavy riffing. Light top for solos, heavy bottom for djent-level chugging. Cobalt wrap wire for enhanced output and harmonics.",
    specs: { gauge: ".010/.013/.017/.030/.042/.052", material: "Cobalt Wound", core: "Hex Core", wound: "Plain .010-.017", coating: "None" },
    tags: ["strings", "guitar", "accessories"],
    isNew: false, isFeatured: false,
  },
  {
    id: 14, name: "BOSS GT-1000 Guitar Processor", brand: "BOSS", category: "accessories",
    price: 28900, salePrice: 25000, sku: "BSS-GT1000",
    stock: 5, rating: 4.5, reviews: 61,
    image: "https://guitar.com/wp-content/uploads/2018/04/boss-gt-1000@1200x900.jpg",
    images: ["https://guitar.com/wp-content/uploads/2018/04/boss-gt-1000@1200x900.jpg"],
    description: "Professional-grade multi-effects with BOSS's AIRD technology. 200+ effects, 128 user patches, USB audio interface, and Bluetooth editor compatibility.",
    specs: { effects: "200+ DSP Effects", patches: "128 User / 128 Preset", amp_models: "50+ AIRD", USB: "Audio/MIDI Interface", power: "AC Adapter" },
    tags: ["effects", "multi-fx", "guitar"],
    isNew: true, isFeatured: false,
  },
  {
    id: 15, name: "Pearl Export 5-Piece Drum Kit", brand: "Pearl", category: "drums",
    price: 24900, salePrice: 21900, sku: "PRL-EXX-725",
    stock: 3, rating: 4.4, reviews: 156,
    image: "https://p.lnwfile.com/_/p/_raw/xj/wu/xl.jpg",
    images: ["https://p.lnwfile.com/_/p/_raw/xj/wu/xl.jpg"],
    description: "Pearl's legendary Export kit — the world's most popular starter-to-intermediate acoustic drum set. Poplar/Asian Mahogany shells, 830-series hardware.",
    specs: { shells: "22x18 BD, 10x7.5/12x8 TT, 16x16 FT, 14x5.5 SD", material: "Poplar/Asian Mahogany", hardware: "830 Series", heads: "Remo Heads Included", finish: "Jet Black" },
    tags: ["drums", "acoustic", "beginner"],
    isNew: false, isFeatured: false,
  },
];

export const CATEGORIES = [
  { slug: "guitar", label: "Guitar", icon: "🎸", count: 5 },
  { slug: "bass", label: "Bass", icon: "🎵", count: 2 },
  { slug: "drums", label: "Drums", icon: "🥁", count: 3 },
  { slug: "keys", label: "Keys & Synths", icon: "🎹", count: 1 },
  { slug: "dj", label: "DJ / Electronic", icon: "🎧", count: 1 },
  { slug: "accessories", label: "Accessories", icon: "🔧", count: 3 },
];

export const BRANDS = ["Fender", "Gibson", "Ibanez", "ESP", "Schecter", "Roland", "Korg", "Pioneer", "Pearl", "DW", "Shure", "BOSS", "Markbass", "Spector", "Ernie Ball"];

export const ORDERS = [
  {
    id: "HF-2024-00142", date: "2024-11-28", status: "Delivered",
    items: [{ name: "ESP LTD EC-1000", qty: 1, price: 35900 }],
    total: 35900, tracking: "TH1234567890",
  },
  {
    id: "HF-2024-00098", date: "2024-10-15", status: "Delivered",
    items: [{ name: "Ernie Ball Strings x5", qty: 5, price: 290 }, { name: "Shure SM57", qty: 1, price: 3500 }],
    total: 4950, tracking: "TH9876543210",
  },
  {
    id: "HF-2024-00201", date: "2024-12-03", status: "Shipped",
    items: [{ name: "Korg Minilogue XD", qty: 1, price: 24900 }],
    total: 24900, tracking: "TH5555666677",
  },
  {
    id: "HF-2024-00218", date: "2024-12-08", status: "Processing",
    items: [{ name: "DW 5000 Double Pedal", qty: 1, price: 15900 }, { name: "Pearl Export 5-Piece", qty: 1, price: 21900 }],
    total: 37800, tracking: null,
  },
];

export const ADMIN_ORDERS = [
  { id: "HF-2024-00218", customer: "Thanapat K.", date: "2024-12-08", items: 2, total: 37800, payment: "Paid", fulfillment: "Processing" },
  { id: "HF-2024-00217", customer: "Supansa W.", date: "2024-12-07", items: 1, total: 72000, payment: "Paid", fulfillment: "Shipped" },
  { id: "HF-2024-00216", customer: "Aroon P.", date: "2024-12-07", items: 3, total: 4230, payment: "Paid", fulfillment: "Delivered" },
  { id: "HF-2024-00215", customer: "Natapon S.", date: "2024-12-06", items: 1, total: 89000, payment: "Pending", fulfillment: "On Hold" },
  { id: "HF-2024-00214", customer: "Ploy J.", date: "2024-12-06", items: 2, total: 38790, payment: "Paid", fulfillment: "Processing" },
  { id: "HF-2024-00213", customer: "Kritsada M.", date: "2024-12-05", items: 1, total: 28000, payment: "Paid", fulfillment: "Delivered" },
  { id: "HF-2024-00212", customer: "Wanchana T.", date: "2024-12-05", items: 4, total: 12340, payment: "Refunded", fulfillment: "Cancelled" },
];

export const REVIEWS = [
  { id: 1, productId: 1, user: "MetalKingTH", rating: 5, date: "2024-11-20", comment: "This guitar shreds. The Seymour Duncans are absolutely crushing — perfect for djent and doom. Build quality is flawless." },
  { id: 2, productId: 1, user: "SixStringSlayer", rating: 5, date: "2024-10-15", comment: "Set-neck feels like a part of my body now. The neck is super fast and the sustain is insane. Best guitar I've owned." },
  { id: 3, productId: 1, user: "GearHead2001", rating: 4, date: "2024-09-30", comment: "Awesome guitar but the stock nut needed some work. Once I got a proper setup from a tech it plays like butter." },
];

export const REVENUE_DATA = [
  { day: "Dec 1", revenue: 45000 }, { day: "Dec 2", revenue: 62000 }, { day: "Dec 3", revenue: 38000 },
  { day: "Dec 4", revenue: 89000 }, { day: "Dec 5", revenue: 74000 }, { day: "Dec 6", revenue: 91000 },
  { day: "Dec 7", revenue: 120000 }, { day: "Dec 8", revenue: 85000 }, { day: "Dec 9", revenue: 67000 },
  { day: "Dec 10", revenue: 110000 }, { day: "Dec 11", revenue: 98000 }, { day: "Dec 12", revenue: 145000 },
];
